source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Oriole_Example', :exclusive => true do
  pod "Oriole", :path => "../"
end

target 'Oriole_Tests', :exclusive => true do
  pod "Oriole", :path => "../"

  pod 'Quick', '~> 0.5.1'
  pod 'Nimble', '2.0.0-rc.2'
end
